#pragma once

#include <stdint.h>
#include <stdlib.h>

typedef unsigned short ADI_DATA_U16;
typedef const uint8_t ADI_REG_TYPE;
typedef uint8_t ADI_REG_U8;

#define SIGMASTUDIOTYPE_FIXPOINT 0
#define SIGMASTUDIOTYPE_INTEGER  1

#define SIGMA_SAFELOAD_DATA_0 0x0810
#define SIGMA_SAFELOAD_DATA_1 0x0811
#define SIGMA_SAFELOAD_DATA_2 0x0812
#define SIGMA_SAFELOAD_DATA_3 0x0813
#define SIGMA_SAFELOAD_DATA_4 0x0814

#define SIGMA_SAFELOAD_ADDR_0 0x0815
#define SIGMA_SAFELOAD_ADDR_1 0x0816
#define SIGMA_SAFELOAD_ADDR_2 0x0817
#define SIGMA_SAFELOAD_ADDR_3 0x0818
#define SIGMA_SAFELOAD_ADDR_4 0x0819

#define SIGMA_SAFELOAD_TRANSFER_BIT 0x081C

#define SIGMASTUDIOTYPE_INTEGER_CONVERT(x) (x)
#define SIGMASTUDIOTYPE_8_24_CONVERT(x)    (x)